name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
    - uses: actions/checkout@v2
=======
    - uses: actions/checkout@v2
>>>>>>> 62c2f7e66db88413a76850deb8a522ad2be5a3bc
